modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/thrasosc/vintage-animations-mod/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "vintage_animations"
version = "${version}"
displayName = "Vintage Animations"
authors = "Thrasos"
credits = "Pixel Dream Studios"
displayURL = "https://modrinth.com/mod/vintage-animations"
description = '''
Overhaul Animations of Basic Actions
'''
logoFile = "icon.png"

[[dependencies.vintage_animations]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vintage_animations]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vintage_animations]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vintage_animations]]
modId = "playeranimator"
type = "required"
versionRange = "[2.0.1+1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vintage_animations]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "vintage_animations.mixins.json"
